name: Run Maven (reactor) build with all components

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to initialize repo with'
        required: false
        default: "${{ github.ref_name }}"

jobs:
  initialize-repo:
    runs-on: ubuntu-24.04

    env:
      BRANCH: "${{ github.event.inputs.branch || github.ref_name }}"

    steps:
      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: |
          repo init \
            "https://github.com/${{ github.repository_owner }}/maven-sources.git" \
            -b "${{ env.BRANCH }}"
          .repo/repo/repo sync

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven 3.9.9
        uses: s4u/maven-settings-action@v2
        with:
          maven-version: '3.9.9'

      - name: Build with Maven
        run: |
          cd sources/aggregator
          mvn clean install -fae
