name: Run Maven (reactor) build with all components

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to initialize repo with'
        required: false
        default: 'master'

jobs:
  initialize-repo:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: sources

      - name: Fetch all git branches
        run: |
          cd sources
          git fetch --all

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: |
          repo init -u sources -m default.xml -b ${{ github.event.inputs.branch || 'master' }}
          repo sync

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven 3.9.9
        uses: s4u/maven-settings-action@v2
        with:
          maven-version: '3.9.9'

      - name: Build with Maven
        run: |
          cd sources/aggregator
          mvn clean install -fae
